title = "hello-world-demo in Civo"
baseURL = "http://CLUSTER_ID.k8s.civo.com/"
theme = "hello-world-demo"
copyright = "© 2020 copyright Civo."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"

[params]
description = ""