
name: Publish Docker image
on: [push]

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
              with:
                ref: ${{ github.head_ref }}
                fetch-depth: 0   

            - name: Git Version
              id: version
              uses: codacy/git-version@2.7.1

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
              
            - name: Build & Push
              run: |
                     docker build . --file ./deployment/Dockerfile --tag ghcr.io/adriseyounis/gcr_demo:${{ steps.version.outputs.version }}
                     docker run ghcr.io/adriseyounis/gcr_demo:${{ steps.version.outputs.version }}
                     docker push ghcr.io/adriseyounis/gcr_demo:${{ steps.version.outputs.version }}