
name: Publish Docker image
on: [push]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build & Push
              run: |
                     docker build . --file ./deployment/Dockerfile --tag ghcr.io/adriseyounis/gcr_demo:latest
                     docker run ghcr.io/adriseyounis/gcr_demo:latest
                     docker push ghcr.io/adriseyounis/gcr_demo:latest